name: CI

on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis:6
        ports:
          - 6379:6379

    env:
      PGPASSWORD: postgres

    steps:
    - uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: install dependencies
      run: |
        make install
        pip freeze

    - name: lint
      run: make lint

    - name: test
      run: |
        make test
        coverage xml

    - uses: codecov/codecov-action@v1.0.13
      with:
        file: ./coverage.xml

  deploy:
    name: Deploy
    needs: test
    if: "success() && startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: install
        run: |
          make install
          pip install -U wheel twine

      - name: build
        run: python setup.py sdist bdist_wheel

      - run: twine check dist/*

      - name: check tag
        run: PACKAGE=foxglove python <(curl -Ls https://git.io/JvQsH)

      - name: upload to pypi
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_token }}
