name: ci

on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request: {}

jobs:
  test:
    name: test py${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis:6
        ports:
          - 6379:6379

    env:
      PGPASSWORD: postgres
      PYTHON: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: install dependencies
      run: |
        make install
        pip freeze

    - run: pytest --cov=foxglove -vv
    - run: coverage xml

    - uses: codecov/codecov-action@v1.0.13
      with:
        file: ./coverage.xml
        env_vars: PYTHON

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'

    - run: pip install -r tests/requirements-linting.txt

    - run: make lint

  deploy:
    needs:
      - test
      - lint
    if: "success() && startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'

      - name: install
        run: pip install -U pip setuptools twine wheel

      - name: set version
        run: VERSION_PATH='foxglove/version.py' python <(curl -Ls https://git.io/JT3rm)

      - run: python setup.py sdist bdist_wheel

      - run: twine check dist/*

      - name: upload to pypi
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_token }}
